# For more info on HTTP files go to https://aka.ms/vs/httpfile

@port=7136
###
GET https://localhost:{{port}}/authors
###
GET https://localhost:{{port}}/books
###
GET GET https://localhost:{{port}}/authors/1
### TODO
GET GET https://localhost:{{port}}/books/1

POST https://localhost:{{port}}/author

Content-Type: application/json

{
  
}

###

### Complete Verbs Here!